### PR TITLE
switch to manual deployment of page

### PR DESCRIPTION
**Pull request by kkmann**
removed gh action to build & publish to gh-pages; manually deply to folder '_site'. Due to issues with quarto gh action #15

### CODE REVIEW

**Comment by danielinteractive** [comment]
Oh that is a pity! Are you sure we need to do that?

**Comment by kkmann** [comment]
It is, couldn't figure out what the issue is. And I think it is more important that we have the polished slides online that that the automatic buidl system works for now. Toothing issues. I even fixed the Quarto version to my local one, same problem :( Happy to switch back but don't want to spend time on it now.

**Comment by danielinteractive** [comment]
@cicdguy any ideas maybe on the quarto build issues mentioned by @kkmann? Just in case...

**Comment by cicdguy** [comment]
I've also had issues with RStudio's Quarto action which is why I resorted to using a container-based workflow. This is what worked for when we used it for our R/Pharma workshop: https://github.com/pharmaverse/cicdworkshop.rinpharma2022/blob/9ec819ff80a3f966bcbf945d928f5fbaa1901f89/.github/workflows/presentations.yml

**Comment by kkmann** [comment]
Great idea, thanks! Will give it a shot.

**Comment by kkmann** [comment]
same issue, oO using a custom rverse derived container - I must be missing something...

**Comment by cicdguy** [comment]
> same issue, oO using a custom rverse derived container - I must be missing something...

Looks like a successful run to me: https://github.com/kkmann/workshop-r-swe/actions/runs/3960498316

**Comment by kkmann** [comment]
it does runs all right, but the artifact (website) is not consistent with what we get locally. Somehow ignores a few quarto options.

**Pull request closed without merging**
